version: "3.8"

services:
  quiz_app:
    container_name: quiz_app
    build:
      context: .
    ports:
      - "8000:5000"
    depends_on:
      - database
    command:
      [
        "./wait-for-it.sh",
        "database:5432",
        "--",
        "python",
        "run.py"
      ]

  database:
    container_name: quiz_database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=quiz
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
